spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    password: hr
  jpa:
    show-sql: true 
server:  port: 5555
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      enabled: true
info:
  build:
    artifactId:'@project.artifact@'
    groupId:'@project.groupId@'
  
  java:
    version:8.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9456/eureka
  